### ISSUE TITLE
"Feature not implemented,tasks route disabled" message throughout the runtime images

### ISSUE THREAD

**Issue by abhishekbhakat** [astronomer/airflow-dbcleanup-plugin#17]
The message `Feature not implemented,tasks route disabled` is bothering a lot of outputs of airflow-cli.

https://github.com/astronomer/airflow-dbcleanup-plugin/blob/4627545e5c47aa0a013d92de218b6785c6f1b33a/utils.py#L26

This needs to be a log message instead of stdout.

**Comment by pgvishnuram** [comment]
fix included closing this PR
